Businesses\Businesses\Products\Code\Tables\Products:
  table: businesses_businesses_products
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      name: title
      type: string
      length: 255
      nullable: false
    description:
      name: description
      type: text
      nullable: false
    business_id:
      name: business_id
      type: integer
      length: 11
      nullable: true
    hit:
      name: hit
      type: integer
      length: 11
      nullable: true
    published:
      name: published
      type: integer
      length: 11
      nullable: true
    created_by:
      name: created_by
      type: integer
      length: 11
      nullable: false
    date_created:
      name: date_created
      type: datetime
      nullable: false
    modified_by:
      name: modified_by
      type: integer
      length: 11
      nullable: false
    date_modified:
      name: date_modified
      type: datetime
      nullable: false
  indexes:
    business_id_index:
      columns: [business_id]
    created_by_index:
      columns: [created_by]
    modified_by_index:
      columns: [modified_by]
  lifecycleCallbacks:
    prePersist:
      - onPrePersist
      - onPrePersistCallbacks
    preUpdate:
      - onPreUpdate
      - onPreUpdateCallbacks
